name: Deploy Multiple Versions

on:
  workflow_dispatch:
  repository_dispatch:
    types: [typescript_update]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          path: main-version

      - name: Checkout TypeScript Version
        uses: actions/checkout@v3
        with:
          ref: gh-pages-typescript
          path: typescript-version

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Main Version Dependencies
        working-directory: main-version/ingredient-recipe-calculator
        run: npm ci

      - name: Build Main Version
        working-directory: main-version/ingredient-recipe-calculator
        env:
          NODE_ENV: production
          PUBLIC_URL: /ingredient-recipe-calculator
        run: npm run build

      - name: Install TypeScript Dependencies
        working-directory: typescript-version/ingredient-recipe-calculator
        run: npm ci

      - name: Build TypeScript Version
        working-directory: typescript-version/ingredient-recipe-calculator
        env:
          NODE_ENV: production
          PUBLIC_URL: /ingredient-recipe-calculator/typescript
        run: npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Prepare deployment
        run: |
          mkdir -p dist
          mkdir -p dist/typescript
          cp -r typescript-version/ingredient-recipe-calculator/build/* dist/typescript/
          cp -r main-version/ingredient-recipe-calculator/build/* dist/
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Ingredient Recipe Calculator - Version Select</title>
              <style>
                body { 
                  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                  margin: 0;
                  padding: 20px;
                  background: #f5f5f5;
                }
                .container { 
                  max-width: 800px; 
                  margin: 50px auto; 
                  text-align: center;
                  background: white;
                  padding: 40px;
                  border-radius: 12px;
                  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                }
                .button-container {
                  display: flex;
                  gap: 20px;
                  justify-content: center;
                  margin-top: 30px;
                }
                .button { 
                  display: inline-block; 
                  padding: 15px 30px; 
                  text-decoration: none; 
                  color: #0366d6; 
                  background: white;
                  border: 2px solid #0366d6;
                  border-radius: 8px;
                  font-weight: 500;
                  transition: all 0.2s ease;
                }
                .button:hover {
                  background: #0366d6;
                  color: white;
                }
                h1 {
                  color: #1a1a1a;
                  margin-bottom: 10px;
                }
                p {
                  color: #666;
                  font-size: 1.1em;
                  margin-bottom: 30px;
                }
              </style>
            </head>
            <body>
              <div class="container">
                <h1>Ingredient Recipe Calculator</h1>
                <p>Please select your preferred version of the application:</p>
                <div class="button-container">
                  <a href="./index.html" class="button">JavaScript Version</a>
                  <a href="./typescript/index.html" class="button">TypeScript Version</a>
                </div>
              </div>
            </body>
          </html>' > dist/version-select.html
          mv dist/version-select.html dist/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 