name: Deploy Multiple Versions

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          path: main-version

      - name: Checkout TypeScript Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages-typescript
          path: typescript-version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Main Version Dependencies
        run: |
          cd main-version/ingredient-recipe-calculator
          npm install
          npm install --save-dev @babel/plugin-proposal-private-property-in-object

      - name: Build Main Version
        run: |
          cd main-version/ingredient-recipe-calculator
          CI=false PUBLIC_URL=/ingredient-recipe-calculator/javascript NODE_ENV=production npm run build

      - name: Install TypeScript Version Dependencies
        run: |
          cd typescript-version/ingredient-recipe-calculator
          npm install

      - name: Build TypeScript Version
        run: |
          cd typescript-version/ingredient-recipe-calculator
          PUBLIC_URL=/ingredient-recipe-calculator/typescript NODE_ENV=production npm run build

      - name: Prepare deployment
        run: |
          rm -rf dist
          mkdir -p dist/javascript
          mkdir -p dist/typescript
          
          # Copy main version to javascript directory
          cp -r main-version/ingredient-recipe-calculator/build/* dist/javascript/
          
          # Copy typescript version from webpack output
          cp -r typescript-version/ingredient-recipe-calculator/dist/* dist/typescript/
          
          # Create version selector page
          cat > dist/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Recipe Calculator - Choose Version</title>
              <style>
                  body { font-family: Arial, sans-serif; max-width: 600px; margin: 40px auto; padding: 0 20px; }
                  h1 { color: #333; text-align: center; }
                  .version-link { display: block; margin: 20px 0; padding: 15px; background: #f5f5f5; 
                                 border-radius: 5px; text-decoration: none; color: #333; text-align: center; }
                  .version-link:hover { background: #e5e5e5; }
              </style>
          </head>
          <body>
              <h1>Recipe Calculator - Choose Version</h1>
              <a href="/ingredient-recipe-calculator/javascript/" class="version-link">JavaScript Version</a>
              <a href="/ingredient-recipe-calculator/typescript/" class="version-link">TypeScript Version</a>
          </body>
          </html>
          EOL

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist
          branch: gh-pages
          clean: true
          single-commit: true 