name: Deploy Multiple Versions

on:
  push:
    branches:
      - pages
      - gh-pages-typescript

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Stable Branch
        uses: actions/checkout@v3
        with:
          ref: pages
          path: stable-version

      - name: Checkout TypeScript Branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages-typescript
          path: ts-version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Build Stable Version
      - name: Build Stable Version
        working-directory: stable-version
        run: |
          npm install
          npm run build
          mkdir -p ../dist/stable
          cp -r build/* ../dist/stable/

      # Build TypeScript Version
      - name: Build TypeScript Version
        working-directory: ts-version
        run: |
          npm install
          npm run build
          mkdir -p ../dist/typescript
          cp -r build/* ../dist/typescript/

      # Update index.html to redirect to versions
      - name: Create Version Index
        run: |
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Ingredient Recipe Calculator - Version Select</title>
              <meta http-equiv="refresh" content="0; url=stable/">
              <style>
                body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
                .container { max-width: 600px; margin: 50px auto; text-align: center; }
                .button { display: inline-block; padding: 10px 20px; margin: 10px; text-decoration: none; 
                         color: white; background: #0366d6; border-radius: 5px; }
              </style>
            </head>
            <body>
              <div class="container">
                <h1>Ingredient Recipe Calculator</h1>
                <p>Please select a version:</p>
                <a href="stable/" class="button">Stable Version</a>
                <a href="typescript/" class="button">TypeScript Version</a>
              </div>
            </body>
          </html>' > dist/index.html

      # Deploy to GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true # Now safe to clean since we're managing all content 