name: Deploy Multiple Versions

on:
  push:
    branches:
      - gh-pages-typescript

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TypeScript Branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages-typescript
          path: ts-version

      - name: Checkout Stable Branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: stable-version
          repository: ${{ github.repository }}
          token: ${{ github.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Copy Stable Version (already built)
      - name: Copy Stable Version
        run: |
          mkdir -p dist/stable
          cp -r stable-version/* dist/stable/

      # Build TypeScript Version
      - name: Build TypeScript Version
        working-directory: ts-version
        run: |
          npm ci
          npm run build
          mkdir -p ../dist/typescript
          cp -r build/* ../dist/typescript/

      # Update index.html to redirect to versions
      - name: Create Version Index
        run: |
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Ingredient Recipe Calculator - Version Select</title>
              <meta http-equiv="refresh" content="0; url=stable/">
              <style>
                body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
                .container { max-width: 600px; margin: 50px auto; text-align: center; }
                .button { display: inline-block; padding: 10px 20px; margin: 10px; text-decoration: none; 
                         color: white; background: #0366d6; border-radius: 5px; }
              </style>
            </head>
            <body>
              <div class="container">
                <h1>Ingredient Recipe Calculator</h1>
                <p>Please select a version:</p>
                <a href="stable/" class="button">Stable Version</a>
                <a href="typescript/" class="button">TypeScript Version</a>
              </div>
            </body>
          </html>' > dist/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 